### ISSUE TITLE
cordova run

### ISSUE THREAD

**Issue by iecxiv** [alfredobs97/adb-wlan-vscode#3]
i connected mi device with > device connect succesfully.
then i run cordova run android --device 
Failed to deploy to device, no device found...
any idea?

**Comment by alfredobs97** [comment]
Can you run?: 
`$ adb devices`

If there are your device in this list, the device had been connected successful, so the cordova CLI is failing, try restarting cordova service

**Comment by iecxiv** [comment]
yes i can run adb devices

**Comment by iecxiv** [comment]
how restart cordova service?

**Comment by alfredobs97** [comment]
Do you see your device in the list when run the command?

I couldn't help you with cordova because I haven't used 😕

**Comment by iecxiv** [comment]
If i connect with cable adb devices is detected. I accept permission of adb on phone, remove cable and connect device with your plugin. Appears notification of succesfully connected. Run cordova run android --device and not connecting...

**Comment by alfredobs97** [comment]
You have to connect first with cable, do the connection and after disconnect the cable
